Added initial tables
turbot/steampipe-plugin-consul pull request #1
Opened 2023-05-08 15:29 UTC by bigdatasourav

2023-05-30 13:41 UTC, madhushreeray30 reviewed
@bigdatasourav can you please look at the review comments, thanks!

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/tables/consul_acl_auth_method.md
> +  consul_acl_auth_method;
```suggestion
  consul_acl_auth_method
```

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/tables/consul_acl_binding_rule.md
> +    on b.auth_method = a.name;
```suggestion
  left join consul_acl_auth_method as a on b.auth_method = a.name;
```

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/tables/consul_acl_role.md
> +  modify_index,
```suggestion
  modify_index
```

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/tables/consul_acl_role.md
Can we build some queries around the `node_identities`, `service_identities`, and `hash` columns?

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/tables/consul_acl_token.md
> +### List tokens which will not expire
```suggestion
### List tokens which will never expire
```

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/tables/consul_intention.md
> +  precedence desc;
The query title says to list the intention with highest precedence however the query ordered them in descending order. I think the title > `List intention with highest precedence` should have limit 1 to it otherwise we should modify the query title and make it > `List intentions in order of highest precedence`.

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/tables/consul_node.md
> +  address
```suggestion
  address,
```

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/tables/consul_node.md
> +  address
```suggestion
  address,
```

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/index.md
> +  service_name
```suggestion
  service_name,
```

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/index.md
> ++------------+--------+---------------+---------------------------------+-----------+
please re-run the query to get the correct output

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/index.md
> +The Consul plugin will use the Consul environment variable to obtain credentials **only if the `address`,`token`, `namespace` and `partition` is not specified** in the connection:
```suggestion
Alternatively, you can also use the standard Consul environment variable to obtain credentials **only if the `address`, `token`, `namespace`, and `partition` is not specified** in the connection:
```

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/index.md
> +export CONSUL_HTTP_ADDR="http://18.118.144.168:4646"
```suggestion
export CONSUL_HTTP_ADDR=http://18.118.144.168:4646
```

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/index.md
> +export CONSUL_NAMESPACE="*"
```suggestion
export CONSUL_NAMESPACE=*
```

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/index.md
> +export CONSUL_HTTP_TOKEN="c178b810-8b18-6f38-016f-725ddec5d58"
```suggestion
export CONSUL_HTTP_TOKEN=c178b810-8b18-6f38-016f-725ddec5d58
```

2023-05-30 13:41 UTC, madhushreeray30 commented on docs/index.md
> +export CONSUL_PARTITION="default"
```suggestion
export CONSUL_PARTITION=default
```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> +
```suggestion

### Install

```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> +### Configuring Consul Credentials
```suggestion
```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> +or you may specify the Address and Token to authenticate:
```suggestion
Or you may specify the address and token to authenticate:
```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> +or if you are using consul enterprise then you may specify the Address, Token, namespace and partition to authenticate:
```suggestion
Or if you are using consul enterprise then you may specify the address, token, namespace, and partition to authenticate:
```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> +or through environment variables
```suggestion
Or through environment variables:
```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> +export CONSUL_HTTP_ADDR="http://18.118.144.168:4646"
```suggestion
export CONSUL_HTTP_ADDR=http://18.118.144.168:4646
```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> +export CONSUL_NAMESPACE="*"
```suggestion
export CONSUL_NAMESPACE=*
```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> +export CONSUL_HTTP_TOKEN="c178b810-8b18-6f38-016f-725ddec5d58"
```suggestion
export CONSUL_HTTP_TOKEN=c178b810-8b18-6f38-016f-725ddec5d58
```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> +export CONSUL_PARTITION="default"
```suggestion
export CONSUL_PARTITION=default
```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> +You may specify the Address to authenticate:
```suggestion
You may specify the address to authenticate:
```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> +  service_name
```suggestion
  service_name,
```

2023-05-30 13:41 UTC, madhushreeray30 commented on README.md
> ++------------+--------+---------------+---------------------------------+-----------+
Please re-run the updated query to get the correct output.

2023-05-30 13:41 UTC, madhushreeray30 commented on consul/table_consul_intention.go
> +		},
```suggestion
		/// Steampipe standard columns
			{
				Name:        "title",
				Description: "The title of the intention",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("ID"),
			},
		},
```

2023-05-30 13:41 UTC, madhushreeray30 commented on consul/table_consul_key.go
> +				Description: "Name is the name of the Key. It must be unique and must be a DNS hostname. There are also other reserved names that may not be used.",
```suggestion
				Description: "Key is the name of the key. It is also part of the URL path when accessed via the API.",
```

2023-05-30 13:41 UTC, madhushreeray30 requested changes
@bigdatasourav can you please look at the review comments, thanks!

2023-05-30 13:41 UTC, madhushreeray30 requested changes
@bigdatasourav can you please look at the review comments, thanks!

2023-05-31 11:58 UTC, madhushreeray30 commented on go.mod
> +require github.com/turbot/steampipe-plugin-sdk/v5 v5.3.0
```suggestion
require github.com/turbot/steampipe-plugin-sdk/v5 v5.4.1
```

2023-06-06 14:53 UTC, misraved approved these changes

2023-06-06 14:54 UTC, madhushreeray30 approved these changes
LGTM 👍

2023-06-06 14:56 UTC, merged